name: CICD

on:
  push:
    branches:
      - my-app

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
      - name: Navigate to my-app folder
        run: cd my-app
      - name: Login to Docker Hub
        run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
      - name: Build Docker Image
        run: docker build -t timeandspacehub/my-app .
      - name: Publish image to docker hub
        run: docker push timeandspacehub/my-app:latest

deploy:
  needs: build
  runs-on: ubuntu-latest
  steps:
    - name: Navigate to my-app folder
      run: cd my-app
    - name: Pull image from Docker Hub
      run: docker pull timeandspacehub/my-app:latest
    - name: Stop and Remove Existing Container
      run: docker stop reactContainer && docker rm reactContainer || true
    - name: Run Docker Container
      run: docker run -d -p 3000:80 --name reactContainer timeandspacehub/my-app:latest